### ISSUE TITLE
pathomit problem

### ISSUE THREAD

**Issue by photopea** [jankovicsandras/imagetracerjs#15] opened 2018-02-10 20:10 UTC
As I understand, "pathomit" omits small particles from the output, but it can create "holes".

I think that these "particles" should be detected at the raster level, they must get another color from the palette (from one of neighbouring colors) and then, the tracing should proceed with this new, adjusted bitmap. 

When you have anti-aliased black-and-white image, thre may be gray pixels between black and white areas, which are not removed by quantization. Does your library deal with it somehow?

**Comment by jankovicsandras** [comment] 2018-02-12 10:38
Hi,

Thanks for the observation!

Before version 1.2, the color layers worked like a stack, and `pathomit` was a very simple solution to remove small particles from the top. I worked fine, because there were other layers under. But it was impossible to get transparent holes in the result, please check [Issue #7 and #8](https://github.com/jankovicsandras/imagetracerjs/issues/8) for more info on this. 

Your suggestion is interesting, but I'm not sure how to implement it yet. I'll think about this. I had a similar idea: instead of removing a small path, it should be merged with a similar color neighbor path. Implementing this seemed somewhat complex to me and I want to keep this project simple. :)

Selective blur can help removing noise as a workaround. Pathomit can be turned off, so I would not file this as a bug, but you're right, pathomit doesn't work as intended, and I'll try to find a solution for this. 

Do you have problem tracing an anti-aliased black-and-white image with `numberofcolors = 2` ?

**Comment by photopea** [comment] 2018-02-12 11:06
I am trying to trace this bitmap:  https://imgur.com/a/r7efs

There are 6 colors: black, white, brown (fur), grey (eye shadows), pink (ears) and transparent
But even if I quantize with 11 colors, eye shadows remain pink (which should be only for ears), and "extra" colors are used for antialiasing (on contours). It is truly a better quantization (has smaller error).

The best I could get with this library was this: http://svgur.com/s/5VW

I made a little change to your algorithm (removing antialiasingand I got this: http://svgur.com/s/5W9

I would like to achieve the results of https://vectormagic.com/ .  I think that a better tracing should not perform quatnization at all, and should take antialiasing into account (to better deduce the original contour).

**Comment by jankovicsandras** [comment] 2018-02-12 19:13
The colors can be preserved by setting a palette manually:

```javascript
options.pal = {"colorquantcycles":1,"pal":[{"r":0,"g":0,"b":0,"a":0},{"r":0,"g":0,"b":0,"a":255},{"r":255,"g":255,"b":255,"a":255},{"r":225,"g":229,"b":228,"a":255},{"r":181,"g":166,"b":144,"a":255},{"r":238,"g":210,"b":215,"a":255}]};
```

But I see your problem with the anti-aliasing artifacts.

**Comment by jankovicsandras** [comment] 2018-02-12 19:24
I got better results with "big" qtres (quadratic spline error treshold), "small" ltres and big pathomit. Still not perfect, but somewhat acceptable.

```javascript
options = {"colorquantcycles":1,"qtres":4,"ltres":0.1,"pathomit":100,"pal":[{"r":0,"g":0,"b":0,"a":0},{"r":0,"g":0,"b":0,"a":255}, {"r":255,"g":255,"b":255,"a":255}, {"r":225,"g":229,"b":228,"a":255}, {"r":181,"g":166,"b":144,"a":255}, {"r":238,"g":210,"b":215,"a":255}]};
```

**Comment by photopea** [comment] 2018-02-12 19:40
Here is how to get the same result as your last options, but without specifying the palette: (i.e. dealing with antialiasing):

Once you have a quantization (index of color for each pixel), loop over all pixels. For each pixel, look at 8 neighbours around it, and replace the pixel index with the most frequent index from neighbours. Put new values into a separate copy, just like you would do when computing a blur.

This makes the "pathomit" parameter redundant.

**Comment by jankovicsandras** [comment] 2018-02-13 12:41
This is a good algorithm, thanks! Please share your code here or create a Pull Request if it's public. :) I'll test this and consider including in the next version. I'm interested in your solution especially because [getting the most frequent element from an array (the neighbor pixels) looks somewhat complex](https://stackoverflow.com/questions/8545590/find-the-most-popular-element-in-int-array), and can have some performance impact if it's performed on every pixel.

However, I'm not sure it can fully replace ```pathomit```. Here's an image why:

![issue15](https://user-images.githubusercontent.com/12699003/36149921-94f5b700-10b9-11e8-86c5-cfda08a0dcc7.png)

Please correct me if I misunderstood this.

**Comment by jankovicsandras** [comment] 2018-02-13 13:18
Here's my naive implementation of your suggested algorithm. This runs ca. 4 seconds on the bunny vs. ca. 1 second without it. I'm sure this can be optimized further.

```javascript
//////// Insert this to line #283.
// Naive pathomit problem #15 suggestion test
// arr2 must be initialized and filled with -1 like arr
for( j=1; j<imgd.height+1; j++ ){
	for(i=1; i<imgd.width+1; i++){
		var neicnt = {};
		for( var k=-1; k<2; k++ ){
			for( var l=-1; l<2 ; l++){
				if(neicnt[''+arr[j+k][i+l]]){
					neicnt[''+arr[j+k][i+l]]++;
				}else{
					neicnt[''+arr[j+k][i+l]] = 1;
				}
			}
		}
		arr2[j][i] = arr[j][i];
		if((j>1)&&(j<imgd.height)&&(i>1)&&(i<imgd.width)){
			var neimax = 0;
			for(var k in neicnt){ 
				if(neicnt[k]>neimax){ 
					arr2[j][i] = parseInt(k);
					neimax = neicnt[k];
				}
			}
		}
	}
}
//////// End of pathomit problem #15 suggestion test
```

**Comment by photopea** [comment] 2018-02-13 14:31
First of all, I recommend to change your representation of an image. Instead of array of arrays, put everything into one array, row by row. So the pixel X,Y, will not be img[y][x], but img[y*width + x];

This can make everything faster and make the memory footprint smaller (and GC friendly), Arrays use some extra memory.

Use an array of offsets to neighbours (converts two nested loops into one loop).

    var nbs  = [-w-1,-w,-w+1,  -1,1,  w-1,w,w+1];

You can keep track of the maximum while going through neighbours.  This "filter" alone takes 30ms for Bunny for me.

**Comment by photopea** [comment] 2018-02-13 14:40
BTW. I understand your example. Maybe instead of choosing the most frequent color from neighbours, we should choose two most frequent colours, and use the one that is more similar to the current color :)

BTW. how much is your algorithm similar to Potrace? http://potrace.sourceforge.net/potrace.pdf

**Comment by jankovicsandras** [comment] 2018-02-13 19:43
Thanks, I'll test your recommendation.

About Potrace: I haven't read this paper before, but **wow**. I mean I knew Potrace (and used it with Inkscape) before, and I downloaded the source in 2015, before I made ImageTracer. I tried to check some of the code, but was overwhelmed, because it's 55+ files just in the /src/ directory and over 380kB (the latest 1.15 version now). And it's in C. I like C, but I wanted to target the browser, so I didn't actually read the code and didn't know how it worked until today.

It's somewhat shocking, but in a good way, how similar the main ideas are. It might sound ridiculous, but it seems I managed to reinvent this wheel. It's not the first epiphany, I've read about [Marching squares](https://en.wikipedia.org/wiki/Marching_squares) in 2017 (vs. ImageTracer is from 2015).
There are some small differences, however:
- Potrace is 2 color only: however this is essentially the same as color quantization -> this color - not this color on every layer
- ImageTracer uses interpolation to get an "octagonal" hull
- The segmentation algorithm seems to be different
- ImageTracer uses only quadratic (3 point) splines vs. the mentioned cubic (4 point) splines in Potrace
- output might be different

Sorry, but I just skimmed the article, will read it soon. I'm still very surprised about the similarity. ImageTracer will also not compete with Potrace: I know (and knew) Potrace is better, I just wanted something simple in Javascript (which is arguably done with 1 file < 50kB). I haven't taken contact with Peter Selinger yet, but I will, thanks for your help. :)

**Comment by photopea** [comment] 2018-02-13 23:15
Here is Potrace in Javascript and it is only 35 kB. https://github.com/kilobtye/potrace   There is a demo, too.

**Comment by photopea** [comment] 2018-03-10 07:22
Hi, this is what I ended up with: https://blog.photopea.com/vectorize-bitmaps-in-photopea.html

**Comment by jankovicsandras** [comment] 2018-03-12 08:09
Photopea.com looks great! :+1:

**Comment by tolyanor** [comment] 2018-04-22 08:58
jankovicsandras, thank you for this lib. Can you help me with same problem? I have artefacts in lines with 45 degrees. You can see it, and try with different options here http://f.dolodom.com/imagetracer/

**Comment by jankovicsandras** [comment] 2018-04-23 07:30
@tolyanor : can you open a new issue? What kind of artefacts do you get? Please take a screenshot, because there are differences in SVG rendering engines, and I know e.g. both Firefox and GIMP SVG engines have rendering problems.

**Comment by jankovicsandras** [comment] 2018-04-24 08:48
@photopea : 

I'm not sure that this problem with the small holes can be fixed with reasonable complexity, because
 - the pixel level information can be translated to multiple correct geometric estimates and
 - there's no guarantee these fill the plane.

![cover_problem](https://user-images.githubusercontent.com/12699003/39175559-319488e0-479a-11e8-982c-7a0a8d331fb9.png)

I've noted these in [Process overview and Ideas for improvement](https://github.com/jankovicsandras/imagetracerjs/blob/master/process_overview.md) , maybe there will be a solution with reasonable complexity someday.

**Closed by jankovicsandras** 2018-04-24 08:48 UTC
Labels: enhancement

**Comment by photopea** [comment] 2018-04-24 08:53
@jankovicsandras  At the end, I ended up not using imagetracerjs , so I am not requiring any fixes.

Wow, you make so many beautiful illustrations! :)  Regarding what you show, I think that the tracer should keep track of adjacent areas, and the "touching contour" should be identical for both shapes.
